# accident evasion
alias rm='rm -i'
alias mv='mv -i'
# ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
# programming
alias lua='lua5.3'
alias g++='g++ -std=c++17'
alias indent='indent -kr'
