# accident evasion
alias rm='rm -i'
alias mv='mv -i'
alias cropdir='cropdir -i'
# ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
# programming
alias lua='lua5.3'
alias g++='g++-8 -std=c++17'
alias indent='indent -kr'
alias gconc='g++-2a -std=c++2a -fconcepts'
